# use make clean to clean up output files from visim.
#
#-----------------------------------------------------------------------

default:
	echo "Use 'make clean' to delete VISIM output files"
clean:
	/bin/rm -rf *.out
