@echo off
cls
echo.
echo          MODFLOW Test Menu
echo.
echo 1. Storage depletion test problem from USGS Open-File Report 88-482,
echo    Leake and Prudic, 1988 (files beginning with ibs)
echo.
echo 2. Example from stream package USGS Open-File Report 88-729 (str)
echo.
echo 3. Example problem in Appendix D of Techniques of Water-Resources
echo    Investigations, book 6, chap. A1 (twri)
echo.
echo 4. Problem 1 from block-centered flow package OFR 91-536 (bcf2ss)
echo.
echo 5. Problem 1 transient leakage package OFR 94-59 (tlkp1)
echo.
echo 6. Example from reservoir package USGS Open-File Report 95-364 (restest)
echo.
echo 7. Example from Flow and Head Boundary Package Open-File Report 97-571 (fhb)
echo.
echo 9. Quit
echo.
echo.
echo To initiate a test, type "go" and the number of the test
echo and then press ENTER (for example, go 1).
echo.
prompt What will it be?:

